# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Set up ENV
      run:  if [ "${{ matrix.java }}" == "8" ]; then
              export IMAGE_NAME="openjdk:8u212-jre-alpine";
            else if [ "${{ matrix.java }}" == "11" ]; then
              export IMAGE_NAME="openjdk:11-jre-stretch";
            fi
    - name: Build with Maven
      run: echo "${IMAGE_NAME}"  && mvn -v
    - name: Codecov
      uses: codecov/codecov-action@v1
